Trainee reports entry creation/update and list (#78)
* Renamed drivers-license-category

* Integrated entities with Trainee and DriversLicenseCat

* Fix imports, typo and lack of @Entity

* Added exports and imports

* Added seeds for trainee reports

* Added controller and service to show reports for trainee

* Removed superadmin managed resources services and controllers

* Basic services and migrations fixed

* Added to FE driversLicenseCategoryId to FIX

* New endpoints to allow creation of empty trainee-reports

* Removal of unused API and new courseReports GET for trainees

* Removal of unused code

* Added migration and indexed columns to allow upsert for trainee report entries

* Fixed migration and entities for changes on upsert

* Added simple vscode settings to fix typescript updated version

* Added findOneByCourseReportId on course report services

* Added reportEntryToCourseReport controllers and services + other components

* Removed reports from course-reports seed

* Added reportEntryGroups integration

* Added unique constraint on description to ensure singularity of records for entryGroups

* Updated function that generates groupedEntries on the course report controller

* Removed TODO comments

* Add FE for trainee report and closing the lesson. Add vehicleId changing to the lesson service

* Add explicit cancel modal

* Add trainee driversLicenseCategory to FE

* Add courseReport DTO

* Fetch report data form the BE

* Fix types

* Fix BE DTOs

* Integrate updating report entries from FE

* Fix TraineesRelationWithLicenses migration

When running this migration from main, we are getting an error that:
QueryFailedError: column "driversLicenseCategoryId" of relation "trainee" contains null values

* Remove commented out code

* Reverse course report generation (trainee generates course report now)

* Fixes reportEntryToCourseReport DTO decorator removal

* Added courseReport.dto to index and updated content for the API response

* Fixed missing error check on createOrModify controller

* Fixed API response content to group differently trainee report content

* Updated trainee controller to error out missing DRIVER LICENSE CATEGORY

* Add my profile (#74)

* Add my profile frontend

* Add backend, integrate BE with frontend

* Fix flashing on / when the user isn't logged in

* Change PUT to PATCH in the update my profile endpoint

* Add payments FE (#76)

* Add payments list for a trainee

* Add payments details and edit

* Update amount to be numeric

* Add adding payments

* Add my payments

* Add TransactionalWithTry (#77)

* Add TransactionalWithTry

* Add eslint plugin, make use of TransactionalWithTry

* Remove test data

* Move some utils directly to TransactionalWithTry

* Replace missing Transactional

* Fixing TransactionalWithTry from Transactional

* Removal reduntant await

* Excluded Report from driver-license-category

* Implementation of new upsert function + controller

* Simplify seedReport generate function

* Adjust response type

* Fix courseReportId

* Remove incorrectly merged button

* Restored files after force push disaster

* Removal of Reports from driverLicenseCategory

---------

Co-authored-by: Bartosz Legięć <bartosz@legiec.io>